languageCode = 'en-us'
title = 'Heavenly-Cyberspace'
theme = 'themes/aafu'
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
[markup.goldmark.renderer]
  unsafe = true

  [[params.menu]]
    name = "Home"
    url = "/"
  [[params.menu]]
    name = "About"
    url = "/about/"
  [[params.menu]]
    name = "Blog"
    url = "/blog/"
  [[params.menu]]
    name = "Articles"
    url = "/articles/"
  [[params.menu]]
    name = "Portfolio"
    url = "/portfolio/"
