name: Hugo deploy

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Hugo
      uses: peaceiris/hugo-action@v2
      with:
        hugo-version: "latest"
        
    - name: Build and deploy
      run: |
        hugo -d public
        git config --global user.name "interstellar-column"
        git config --global user.email "interstellarcolumn@heavenly-cyberspace.xyz"
        git add -A
        git commit -m "Deployed to GitHub Pages"
        git push -u origin gh-pages
